### ISSUE TITLE
Error: no such package

### ISSUE THREAD

**Issue by titocosta** [roelvan/meteor-readmore#1]
Hello roelvan, thanks for putting this together.

When invoking:

```
meteor add rova:jquery-readmore
```

I get the following error message:

```
=> Errors while parsing arguments: 
While adding package rova:jquery-readmore:
error: no such package
```

**Comment by roelvan** [comment]
Hi man,

Yes I had some problems publishing my package, so it is not yet on the official Meteor packages server.

You can use this zip: `http://cl.ly/3j2r3z1l2G2I` and copy paste it under `/packages`, then run `meteor add jquery-readmore`.

On of these days it should be available on atmospherejs... Depending on my schedule :)

**Comment by titocosta** [comment]
Thanks, it works great.
